version: '2'
services:
  seed:
    image: org.loopring/lightcone_actors:latest
    shm_size: 800m  #shm_size指定
    ports:    #端口映射
      - "2552:2552"
    volumes:
      - "./seed_log:/log"   #映射log目录
    environment:
      CLUSTER_IP: seed
      CLUSTER_PORT: 2552
      SEED_IP: seed
      NODE_ROLES: '[
        "database_query",
        "ethereum_event_extractor",
        "ethereum_query",
        "gas_price",
        "market_manager",
        "multi_account_manager",
        "orderbook_manager",
        "order_cutoff_handler",
        "order_persistence",
        "order_recover",
        "order_recover_coordinator",
        "order_status_monitor",
        "ring_settlement",
        "transaction_record"
      ]'
  ethereum:
    image: org.loopring/lightcone_actors:latest
    shm_size: 500m
    volumes:
      - "./ethereum_log:/log"
    environment:
      CLUSTER_IP: ""  #为空，选择随机ip
      CLUSTER_PORT: 2552  #为空,可以选择随机端口
      SEED_IP: seed
      NODE_ROLES: '[
        "ethereum_access",
        "ethereum_client_monitor"
      ]'
  entrypoint:
    image: org.loopring/lightcone_actors:latest
    shm_size: 500m
    volumes:
      - "./entrypoint_log:/log"
    environment:
      CLUSTER_IP: ""  #为空，选择随机ip
      CLUSTER_PORT: 2552  #为空,可以选择随机端口
      SEED_IP: seed
      NODE_ROLES: '[
        "entrypoint",
        "jsonrpc"
      ]'

#可以选择docker内网地址
#networks:
#  app_net:
#    driver: bridge