version: '2'
services:
  seed:
    image: org.loopring/lightcone_actors:latest
    shm_size: 800m  #shm_size指定
    ports:    #端口映射
      - "2552:2552"
    volumes:
      - "./log:/log"   #映射log目录
    environment:
      CLUSTER_IP: seed
      CLUSTER_PORT: 2552
      SEED_IP: seed
      NODE_ROLES: '["a", "b", "c"]'
  worker:
    image: org.loopring/lightcone_actors:latest
    shm_size: 500m
    volumes:
      - "./log:/log"
    environment:
      CLUSTER_IP: ""  #为空，选择随机ip
      CLUSTER_PORT: 2552  #为空,可以选择随机端口
      SEED_IP: seed
      NODE_ROLES: '["a", "b", "c"]'

#可以选择docker内网地址
#networks:
#  app_net:
#    driver: bridge